gateways:
  postgres:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/postgres/#connection-options
      type: bigquery
      project: {{env_var('BQ_ID')}}
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: True
      # pretty_sql: False
      # keepalives_idle: 
      # connect_timeout: 10
      # role: 
      # sslmode: 


default_gateway: postgres

model_defaults:
  dialect: bigquery
  start: 2025-02-18
